---
apiVersion: v1
kind: Namespace
metadata:
  name: cloud-ruby
  labels:
    monitor-pods-datasets: enabled
---
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
spec:
  local:
    bucket: cloud-ruby
    endpoint: "https://s3.us-east-2.amazonaws.com/cloud-ruby"
    readonly: "false"
    region: us-east-2
    secret-name: cluster-user-creds
    secret-namespace: cloud-ruby
    type: COS
metadata:
  name: s3-dataset
  namespace: cloud-ruby

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ruby
  namespace: cloud-ruby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-ruby
  template:
    metadata:
      labels:
        app: cloud-ruby
    spec:
      containers:
        - name: application
          image: brianberzins/cloud-ruby:latest
          ports:
            - containerPort: 4567
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - mountPath: /public
              name: s3-storage
              readOnly: false
          livenessProbe:
            httpGet:
              path: /hello-world
              port: 4567
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /hello-world
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 2
      volumes:
        - name: s3-storage
          persistentVolumeClaim:
            claimName: s3-dataset

---
apiVersion: v1
kind: Service
metadata:
  namespace: cloud-ruby
  name: cloud-ruby
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: cloud-ruby
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4567
