kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # used to connect via node-port (see service definition in local-deployment.yml)
      - containerPort: 30950
        hostPort: 80
