name: "Deploy to KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          skipClusterCreation: true
      - name: KinD Testing
        run: ./local-test.sh

  docker:
    needs: kind
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: brianberzins
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Publish
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            brianberzins/cloud-ruby:latest
            brianberzins/cloud-ruby:${{ github.sha }}

  deploy:
    needs: docker
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: install kubectl
        id: install
        uses: azure/setup-kubectl@v2.0
      - name: Cloud Deploy
        env:
          KUBECONFIG_BASE64_CONTENTS: ${{ secrets.KUBECONFIG_BASE64_CONTENTS }}
          IMAGE_TAG: brianberzins/cloud-ruby:${{ github.sha }}
        run: ./cloud-depoy.sh
